### ISSUE TITLE
Client::currentsong() indefinitely blocking

### ISSUE THREAD

**Issue by Kilobyte22** [kstep/rust-mpd#1] opened 2015-12-12 18:46 UTC
I just tried to use this library to query an mpd server for the current song played. However the currentsong() call blocks forever, even though the server replies correctly. I have not managed to find out why, so i am opening this issue.

Example Code:
```rust
match c.currentsong().unwrap() {
  Some(s) => {
    println!("{}", s.name.unwrap());
  },
   None => {}
}
```

**Comment by kstep** [comment] 2015-12-12 20:17
Thank you very much for the info!
I'll try to look into it asap.

**Comment by kstep** [comment] 2015-12-12 20:37
Could you also please give me some more background?
I'm interested in MPD version number and messages log.

**Comment by Kilobyte22** [comment] 2015-12-12 22:46
```
OK MPD 0.19.0
currentsong
file: Massive_Attack/2003 - 100th Window/06. A Prayer For England.mp3
Last-Modified: 2007-07-30T18:16:07Z
Artist: Massive Attack
Title: A Prayer For England
Album: 100th Window
Track: 06
Date: 2003
Genre: Trip-Hop
Time: 349
Pos: 106
Id: 370
OK
```
Should be easy to see which messages were send by which end.

**Comment by kstep** [comment] 2015-12-14 12:51
I could not reproduce the bug on my local machine. Does your code even connects to MPD? Do you run MPD and your code on the same machine?

**Comment by kstep** [comment] 2015-12-14 13:38
Also, if you could run your example code with strace, it would help a lot.

**Comment by Kilobyte22** [comment] 2015-12-14 19:20
1. Yes it does connect
2. Interestingly when running against a local test server, it does work.
3.
```
execve("target/debug/mpdi3block", ["target/debug/mpdi3block"], [/* 72 vars */]) = 0
brk(0)                                  = 0x55ec60fde000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=137967, ...}) = 0
mmap(NULL, 137967, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1140bd1000
close(3)                                = 0
open("/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=14576, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1140bd0000
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f11407ce000
mprotect(0x7f11407d1000, 2093056, PROT_NONE) = 0
mmap(0x7f11409d0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f11409d0000
close(3)                                = 0
open("/usr/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@a\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=146608, ...}) = 0
mmap(NULL, 2213008, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f11405b1000
mprotect(0x7f11405c9000, 2093056, PROT_NONE) = 0
mmap(0x7f11407c8000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f11407c8000
mmap(0x7f11407ca000, 13456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f11407ca000
close(3)                                = 0
open("/usr/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260*\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=532440, ...}) = 0
mmap(NULL, 2185504, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f114039b000
mprotect(0x7f11403b1000, 2093056, PROT_NONE) = 0
mmap(0x7f11405b0000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f11405b0000
close(3)                                = 0
open("/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\7\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1991416, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1140bcf000
mmap(NULL, 3815984, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f113fff7000
mprotect(0x7f1140192000, 2093056, PROT_NONE) = 0
mmap(0x7f1140391000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19a000) = 0x7f1140391000
mmap(0x7f1140397000, 14896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1140397000
close(3)                                = 0
open("/usr/lib/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20U\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1038688, ...}) = 0
mmap(NULL, 3133720, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f113fcf9000
mprotect(0x7f113fdf6000, 2093056, PROT_NONE) = 0
mmap(0x7f113fff5000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xfc000) = 0x7f113fff5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1140bce000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1140bcc000
arch_prctl(ARCH_SET_FS, 0x7f1140bcc800) = 0
mprotect(0x7f1140391000, 16384, PROT_READ) = 0
mprotect(0x7f113fff5000, 4096, PROT_READ) = 0
mprotect(0x7f11407c8000, 4096, PROT_READ) = 0
mprotect(0x7f11409d0000, 4096, PROT_READ) = 0
mprotect(0x7f1140bf3000, 4096, PROT_READ) = 0
munmap(0x7f1140bd1000, 137967)          = 0
set_tid_address(0x7f1140bccad0)         = 15062
set_robust_list(0x7f1140bccae0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f11405b6be0, [], SA_RESTORER|SA_SIGINFO, 0x7f11405c1d60}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f11405b6c70, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f11405c1d60}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
readlink("/etc/je_malloc.conf", 0x7fffd38463d0, 4096) = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x55ec60fde000
mmap(NULL, 4194304, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f113f8f9000
munmap(0x7f113f8f9000, 4194304)         = 0
mmap(NULL, 8384512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f113f4fa000
munmap(0x7f113f4fa000, 3170304)         = 0
munmap(0x7f113fc00000, 1019904)         = 0
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-1\n", 8192)                  = 4
close(3)                                = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f114002a680}, {SIG_DFL, [], 0}, 8) = 0
brk(0x55ec60fff000)                     = 0x55ec60fff000
open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1140bf2000
read(3, "55ec5edad000-55ec5ee3e000 r-xp 0"..., 1024) = 1024
read(3, "-7f1140395000 r--p 0019a000 00:1"..., 1024) = 1024
read(3, "                 /usr/lib/libdl-"..., 1024) = 1024
close(3)                                = 0
munmap(0x7f1140bf2000, 4096)            = 0
sched_getaffinity(15062, 32, {3, 0})    = 16
mmap(0x7fffd3049000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fffd3049000
rt_sigaction(SIGSEGV, {0x55ec5edef9b0, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7f11405c1d60}, NULL, 8) = 0
rt_sigaction(SIGBUS, {0x55ec5edef9b0, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7f11405c1d60}, NULL, 8) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1140bf1000
sigaltstack({ss_sp=0x7f1140bf1000, ss_flags=0, ss_size=8192}, NULL) = 0
mmap(NULL, 4194304, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f113f400000
open("/home/stephan/.mpdhosts", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, FIOCLEX)                       = 0
read(3, "10.0.1.6:6601:Labor Lounge\n", 32) = 27
read(3, "", 5)                          = 0
write(1, "Connecting to Labor Lounge\n", 27Connecting to Labor Lounge
) = 27
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
ioctl(4, FIOCLEX)                       = 0
connect(4, {sa_family=AF_INET, sin_port=htons(6601), sin_addr=inet_addr("10.0.1.6")}, 16) = 0
read(4, "OK MPD 0.19.0\n", 65536)       = 14
write(1, "Done with Labor Lounge\n", 23Done with Labor Lounge
) = 23
write(1, "Trying host Labor Lounge\n", 25Trying host Labor Lounge
) = 25
sendto(4, "currentsong\n", 12, 0, NULL, 0) = 12
read(4, "file: R\303\266yksopp/The Understandin"..., 65536) = 257
read(4,
```

**Comment by kstep** [comment] 2015-12-14 20:26
Uh oh, looks like an error in parser. Could you please give me the full song file name it stops at? The one starting with `"R\303\266yksopp/The Understanding"`.

**Comment by Kilobyte22** [comment] 2015-12-15 00:17
I cannot give you that, however the log i gave you last time causes exactly the same issue. I am currently not able to connect to that very mpd, but i think it is an interaction issuue between that very version and your code. If you (or i, possibly tomorrow) can get that very version, it should be possible to reproduce.

**Comment by kstep** [comment] 2015-12-15 09:16
Do you play the same playlist with the same songs on local environment, where the code works?

**Comment by Kilobyte22** [comment] 2015-12-15 11:15
I do not have access to the server i am having trouble with, but i can try getting access. This probably won't be before friday though

**Comment by kstep** [comment] 2015-12-15 12:12
Ok then, I'll wait till then. As of now, I couldn't reproduce the bug (MPD 0.19.0, both remote and local server works, adding "o with umlaut" (`ö`) to the file name doesn't affect tests).

**Comment by kstep** [comment] 2015-12-15 12:15
Just thought about a thing to check: what is the value of MTU between you and your server? As I can see, first request-respond series are quite short, and it hangs on the last read, which is longer than other responses. Sometimes small MTU can lead to such effects.

**Comment by kstep** [comment] 2015-12-15 12:17
Just to be clear: I don' expect you to answer immediately, just listing a things I thought about. Feel free to check and answer when/if you can.

**Comment by Kilobyte22** [comment] 2015-12-15 12:46
i did use netcat to connect to the server and issued the currentsong command manually, it did work. That is how i got the log. I then hosted a server using netcat, connected with your library to it and sent exactly what the server sent. Even with that i could reproduce the issue.

**Comment by kstep** [comment] 2015-12-15 18:42
Hey, it just came to me. You can create TcpStream manually, set_read_timeout() on it and build client with Client::new(). It should at least make transmission fail on timeout.

**Comment by Kilobyte22** [comment] 2015-12-16 07:52
that sounds like a pretty good idea, will definitely try that.

**Comment by Kilobyte22** [comment] 2015-12-18 16:25
So, here are the details:
Network log: https://kilobyte22.de/files/rust-mpd-netlog.bin
strace of that very same execution: https://gist.github.com/Kilobyte22/4ca71fc938e5c164ac8f

Note this is is with timeout (5 seconds) enabled. The issue seems to not occur while no music is playing - at least not consistantly.

**Comment by Kilobyte22** [comment] 2015-12-21 11:55
I am not sure, you may have missed my last reply.

**Comment by kstep** [comment] 2015-12-21 13:36
Hey, I'm sorry for long silence. I've got your message, I was just too busy IRL. I don't think it's about line-endings, I thought about it, and there's no difference between working and not working examples in line endings. Special characters doesn't matter as well. As a matter of fact, I couldn't reproduce the bug, and as of now I'm low on theories.

**Comment by Kilobyte22** [comment] 2015-12-21 15:28
Just out of curiousity, what version of rust are you using. I was using `rustc 1.7.0-nightly (7ce713961 2015-12-11)` until now, will upgrade to latest nightly now and report back.

**Comment by kstep** [comment] 2015-12-21 16:16
rustc 1.7.0-nightly (81ae8be71 2015-12-09)

**Comment by Kilobyte22** [comment] 2015-12-21 22:25
I could reproduce it with latest rust. The very same server runs multiple mpd instances. I could reproduce it on only one of them, but that was without music running. Could not actually test with music playing, will do when next possible. Will also talk to the admin about this, maybe we can figure it out or give you valuable detail.

**Comment by kstep** [comment] 2015-12-21 22:34
Yes, that would be very useful, thank you! Meanwhile I'll also try to reproduce it with several mpd instances running on my server.

**Comment by GTB3NW** [comment] 2016-01-05 17:43
I have the same issue. If I wait a while it eventually works. Talking upwards of 1 minute for a response.

mpd version: 0.19.0
rustc 1.5.0

Would you like me to test anything now you have another user confirmed to have the issue?

**Comment by kstep** [comment] 2016-01-05 18:55
@GTB3NW yes, could you please describe your setup? Like do you run mpd locally or remotely, single or multiple instances of mpd, internal network or via internet, VPN? I'd like to find anything common with @Kilobyte22's environment.

**Comment by GTB3NW** [comment] 2016-01-05 19:47
Local MPD, single instance. nc'd to the server and ran "currentsong" it works fine.

Here's the output of the command if you need reference:

```
OK MPD 0.19.0
currentsong
file: Justice/Audio, Video, Disco/06 On'n'On.flac
Last-Modified: 2014-10-22T18:20:48Z
Genre: Indie Rock
Composer: Gaspard Augé, Xavier de Rosnay
Title: On'n'On
MUSICBRAINZ_ALBUMARTISTID: 860b2707-6153-4e3a-aa57-74d2b42c55b5
Date: 2011
Disc: 1
AlbumArtistSort: Justice
MUSICBRAINZ_ALBUMID: 5bda6888-71a8-4fa7-9625-a88122e2435c
AlbumArtist: Justice
Album: Audio, Video, Disco
MUSICBRAINZ_ARTISTID: 860b2707-6153-4e3a-aa57-74d2b42c55b5
Artist: Justice
MUSICBRAINZ_TRACKID: 0e5d05c8-f89d-4420-99a7-f4e9a0c68fff
ArtistSort: Justice
Track: 6
Time: 271
Pos: 8
Id: 25
OK
```

**Comment by kstep** [comment] 2016-01-05 20:28
Thank you very much! Can you tell me please on which line does `Client::currentsong()` method hangs? You can run your example code under strace to find it out.

**Comment by GTB3NW** [comment] 2016-01-05 20:43
Where it detaches is where it's hanging:

```
mmap(0x7ffdefe3a000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ffdefe3a000
rt_sigaction(SIGSEGV, {0x561e9ab52a00, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fab7e056d60}, NULL, 8) = 0
rt_sigaction(SIGBUS, {0x561e9ab52a00, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x7fab7e056d60}, NULL, 8) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fab7e686000
sigaltstack({ss_sp=0x7fab7e686000, ss_flags=0, ss_size=8192}, NULL) = 0
mmap(NULL, 4194304, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fab7cc00000
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
ioctl(3, FIOCLEX)                       = 0
connect(3, {sa_family=AF_INET, sin_port=htons(6600), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
read(3, "OK MPD 0.19.0\n", 65536)       = 14
sendto(3, "currentsong\n", 12, 0, NULL, 0) = 12
read(3, "file: Justice/Audio, Video, Disc"..., 65536) = 564
read(3, ^CProcess 20172 detached
 <detached ...>
```

**Comment by kstep** [comment] 2016-01-05 21:00
Thank you very much! You helped a lot! I think I have an idea to check. I'll post back when I check it.

**Comment by GTB3NW** [comment] 2016-01-05 21:23
Just as an FYI. After the 1 minute timeout the returned data just has null values, so:

    println!("{}", song.file);

prints:

    {}

Is the format of the currentsong request any different to the current queue/playlist? This is the first song returned when I run "playlistinfo" in nc:

```
file: Justice/✝/1-02 Let There Be Light.flac
Last-Modified: 2014-10-22T18:19:51Z
Genre: Electronic
AlbumArtist: Justice
Title: Let There Be Light
MUSICBRAINZ_ALBUMARTISTID: 860b2707-6153-4e3a-aa57-74d2b42c55b5
Date: 2007-06
Disc: 1
AlbumArtistSort: Justice
MUSICBRAINZ_ALBUMID: f1d8e333-c047-49eb-a6a7-e5b842895fe9
AlbumArtist: Justice
Album: ✝
MUSICBRAINZ_ARTISTID: 860b2707-6153-4e3a-aa57-74d2b42c55b5
Artist: Justice
MUSICBRAINZ_TRACKID: 5e10ccfe-eb20-4c51-95cb-b5edc143556e
ArtistSort: Justice
Track: 2
Time: 301
Pos: 0
Id: 11
```

**Comment by kstep** [comment] 2016-01-05 21:45
@GTB3NW Hmm, both you and @Kilobyte22 get whole MPD song info read in the single first `read()` request (according to number of read bytes returned from `read()`), but after that Rust thinks there must be something after it, and it issues another `read()`, which hangs because MPD already sent everything it wants.

I tried to reproduce it on my laptop, and I see single `read()` request which reads whole MPD currentsong answer, and then no other reads after it, and it works OK.

**Comment by Kilobyte22** [comment] 2016-01-05 21:49
Maybe the bug is actually in the rust standard library, possibly caused by mpd not sending utf-8 (not sure which encoding it uses)

**Comment by kstep** [comment] 2016-01-05 21:52
As far as I can tell, MPD doesn't bother about encodings, it just passes around raw strings, as read from tags/file names. I have several songs with windows-1251 encoded tags, and it sends them as raw bytes, so I see strange symbols in ympd, which uses utf-8 only:

![2016-01-06-005146_551x73_scrot](https://cloud.githubusercontent.com/assets/28537/12128653/b9fe39ae-b40f-11e5-8546-7a9c0ad5267b.png)

**Comment by kstep** [comment] 2016-01-05 21:54
It still works with rust-mpd on my laptop, even when this song is being played, I just get some funky data in tags:

```
    tags: {
        "Album": "Social Song",
        "Artist": "\u{dd}\u{ea}\u{f1}\u{eb}\u{fe}\u{e7}\u{e8}\u{e2}\u{ed}\u{ee}! \u{d2}\u{ee}\u{eb}\u{fc}\u{ea}\u{ee} \u{e4}\u{eb}\u{ff} \u{ec}\u{ee}\u{e8}\u{f5} \u{e4}\u{f0}\u{f3}\u{e7}\u{e5}\u{e9} \u{e2}\u{ea}\u{ee}\u{ed}\u{f2}\u{e0}\u{ea}\u{f2}\u{e5} \u{f1}\u{e5}\u{e3}\u{ee}\u{e4}\u{ed}\u{ff} \u{e2}\u{fb}\u{f8}\u{e5}\u{e4}\u{f8}\u{e8}\u{e9} \u{ed}\u{ee}\u{e2}\u{fb}\u{e9} \u{f2}\u{f0}\u{e5}\u{ea} \u{dd}\u{ed}\u{e8}\u{e3}\u{ec}\u{fb}, \u{f1}\u{e0}\u{ec}\u{fb}\u{e9} \u{f1}\u{e2}\u{e5}\u{e6}\u{e8}\u{e9}",
        "Composer": "Alise Ketnere (Fox Lima) / Marcelo Amaral Pontello (Mark Joshua) J\u{e9}r\u{f4}me Pringault (J. Spring) / Rasa Veretenceviene (Rasa Serra)",
        "Date": "2010",
        "Genre": "New Age",
        "Title": "2010 (\u{ee}\u{f0}\u{e8}\u{e3}\u{e8}\u{ed}\u{e0}\u{eb}\u{fc}\u{ed}\u{ee}\u{e5} \u{ed}\u{e0}\u{e7}\u{e2}\u{e0}\u{ed}\u{e8}\u{e5}, \u{ff} \u{e4}\u{ee}\u{e1}\u{e0}\u{e2}\u{e8}\u{eb} \u{ee}\u{e1}\u{eb}\u{ee}\u{e6}\u{ea}\u{f3} \u{e2} \u{e0}\u{f3}\u{e4}\u{e8}\u{ee}, download & relax)",
        "Track": "1/1"
    }
```

**Comment by kstep** [comment] 2016-01-05 21:55
Not sure about really *invalid* UTF-8 sequences, maybe my case contains de facte valid UTF-8 codepoints, which just don't make sense for us humans.

**Comment by Kilobyte22** [comment] 2016-01-05 22:05
They don't have to be invalid. They can have a different meaning. UTF-8 characters can be longer than one byte. This way it can actually trick the program into thinking that for example that the line break is part of another character. I'm not sure if this is the case, would have to take a closer look at this.

**Comment by kstep** [comment] 2016-01-05 22:09
I posted a question to Rust users forum: https://users.rust-lang.org/t/issues-with-std-io-lines-read-blocks-forever/4181
Hope they will provide some fresh ideas on the matter.

**Comment by kstep** [comment] 2016-01-05 22:13
@Kilobyte22 it *might* be the case, but your own printout of a song info you have problems with looks like pretty much valid ASCII for me:

```
OK MPD 0.19.0
currentsong
file: Massive_Attack/2003 - 100th Window/06. A Prayer For England.mp3
Last-Modified: 2007-07-30T18:16:07Z
Artist: Massive Attack
Title: A Prayer For England
Album: 100th Window
Track: 06
Date: 2003
Genre: Trip-Hop
Time: 349
Pos: 106
Id: 370
OK
```

This disproves this theory, unless I miss something here?

**Comment by Kilobyte22** [comment] 2016-01-05 22:14
That's what I thought of myself as well, but maybe I am missing something myself so I wanted to bring that up.

**Comment by GTB3NW** [comment] 2016-01-05 22:33
Even if there's an issue with that, would it affect the parsing of it? Like I pointed out MPD sends the data but rust-mpd doesn't parse it correctly. It's only incorrectly parsing it in the currentsong method, fetching queue etc it works fine. Would be a good start to look at any difference between the data MPD sends from the current playlist (queue) and the currentsong.

**Comment by kstep** [comment] 2016-01-06 01:38
According to strace, it's pretty normal, that you get empty result, as it hangs immediately on the first try to read first reply line. That is, even the first read_line() never returns, and parser even don't get anything to parse.

**Comment by kstep** [comment] 2016-01-06 01:38
The funky thing happens on read line operation, for sure.

**Comment by kstep** [comment] 2016-01-06 01:41
BTW, just to be sure, on what OS does your MPD server and client runs?

**Comment by Kilobyte22** [comment] 2016-01-06 02:47
Client: Arch Linux x86_64
Server: Linux, Unknown distribution. I suspect Debian though

**Comment by kstep** [comment] 2016-01-06 14:48
One last question for now. Could one of you reproduce the bug with test program running under `strace -e read,sendto -s 2000` so the whole read string is visible in a dump? Just to make sure what it reads up to the end of reply.

**Comment by GTB3NW** [comment] 2016-01-06 15:05
My client and server is on arch too.

I'd laugh if this was an arch specific bug.

I'll test when I'm back from work.

**Comment by kstep** [comment] 2016-01-06 15:43
Oh ho, seems like I found the problem. It is a bug in v0.0.7, which is fixed in master now.
I've published updated version, so you it should be fixed once you update to 0.0.8.

**Comment by kstep** [comment] 2016-01-06 15:43
After you update to 0.0.8, please confirm it resolved the bug. I will close the issue then.

**Comment by Kilobyte22** [comment] 2016-01-06 15:44
Just curious, what was the issue?

**Comment by kstep** [comment] 2016-01-06 15:49
The issue was in incorrect data reading sequence in `currentsong()` method, I rewritten ages ago and completely forgot about it. It just came to me to check library version, and just noticed the last version I published was 0.0.7, then I compared tag v0.0.7 with master and the bug was pretty obvious. Sorry it took so long to find it all out.

**Comment by kstep** [comment] 2016-01-06 15:50
The bug was actually fixed by 31fef68b16993a3c5be501f1d2a11b5d4227c468 on Jun 26th, 2015.

**Comment by GTB3NW** [comment] 2016-01-06 16:20
Lmao, woops! Will test in an hour and let you know. Thanks! 😀

**Comment by Kilobyte22** [comment] 2016-01-06 16:31
I should be able to test tomorrow as well

**Comment by GTB3NW** [comment] 2016-01-07 20:55
Sorry forgot to update you. Works great, thanks! :)

**Closed** 2016-01-08 05:54 UTC

**Comment by Kilobyte22** [comment] 2016-01-12 14:54
Yep, works fine for me as well, thanks for taking your time :)
